### ISSUE TITLE
Can this repo wokrs on esp32c3?

### ISSUE THREAD

**Issue by jd3096-mpy** [russhughes/gc9a01_mpy#13]
I try to build firmware ,build success but start failed.
Can you provied a firmware for esp32c3-usb？Thanks.

**Comment by russhughes** [comment]
It should work.  I have compiled firmware for the GENERIC_C3 and GENERIC_C3_USB boards but have not tested them.  I

**Comment by jd3096-mpy** [comment]
> It should work. I have compiled firmware for the GENERIC_C3 and GENERIC_C3_USB boards but have not tested them. I

I found out the reason.
I use latest micropython 1.20.0 repo to build this firmware,but it seems they changed the way to add extra c modules.

Any third-party C extensions will need to be updated to work with this change. See commits https://github.com/micropython/micropython/commit/662b9761b37b054f08fe2f7c00d0fce3a418d0b0 and https://github.com/micropython/micropython/commit/3ac8b5851e5f4dade465d52b91ed2ccc17851263 for details.

[https://github.com/micropython/micropython/releases](url)

**Comment by jd3096-mpy** [comment]
> It should work. I have compiled firmware for the GENERIC_C3 and GENERIC_C3_USB boards but have not tested them. I

Thanks for your firmware,it test it and it works good.
![f852da246870ff8726b15cbef3c8886](https://user-images.githubusercontent.com/69076780/235047346-a1931abf-4736-4d5c-9e1c-bf8742ac7766.jpg)

But I still need time to checkout why the firmware build by myself started faild,you can close this issue.
