### ISSUE TITLE
How to Build RPi Pico Firmware for MicroPython v1.20 / latest?

### ISSUE THREAD

**Issue by ciobania** [russhughes/gc9a01_mpy#15]
Hey, 

thank you for the library, and support.
Can you please tell me what is the command to / parameters to build this with the latest MicroPython version v1.20 for RPi Pico W?

More specifically, I'm struggling to understand the 2 following instructions:

*Where is this from, how do I get the `micropython/ports/esp32`?
```
$ cd micropython/ports/esp32

And then compile the module with specified USER_C_MODULES dir

$ make USER_C_MODULES=../../../../gc9a01_mpy/src/micropython.cmake all
```
 
There are some new changes in that, that I really need, and not sure how to do this.

Thank you.

**Comment by russhughes** [comment]
Those errors usually indicate that CMake is not finding your C and C++ compilers or you need a newer version of CMake.
