### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by anscarlett** [russhughes/gc9a01_mpy#2]
Hi,

I'm trying this on a pi Pico connected to a waveshare display, but I can't get anything to work except the backlight. I uploaded the firmware and saved an example to the pi, and I get no errors, but nothing happens. I tried setting a background colour and a few other functions, but the only ones that seem to work are on and off for the backlight.

This is on a fresh Pico pi, using thonny.

Anyone got any idea?

**Comment by russhughes** [comment]
Which display pins are connected to which PICO pins and what are your gc9a01.GC9A01() parameters?
