### ISSUE TITLE
Fonts not available in self-build firmware

### ISSUE THREAD

**Issue by MrTheRich** [russhughes/gc9a01_mpy#21]
I build the esp32 firmware port including this framework according to your guide. The module for the screen is available, but non of the fonts show up available for import. Did i miss anything in the guide or did someone forget to put it in? I'd like to have at least 1 font available to display text.

**Comment by russhughes** [comment]
Copy any .py files you want to include in the firmware as frozen Python modules to the micropython/ports/esp32/modules folder.
