### ISSUE TITLE
Support for muliple GC9A01 display

### ISSUE THREAD

**Issue by shrynikjain** [russhughes/gc9a01_mpy#28]
GC9A01 display(round display): Its not supoorting for multiple display. We are using esp32. Code format:
spi =SPI(1, baudrate=60000000, sck=Pin(11), mosi=Pin(12))   
for first display
tft = gc9a01.GC9A01(spi,240,240,reset=Pin(9, Pin.OUT),cs=Pin(3, Pin.OUT),dc=Pin(46, Pin.OUT)backlight=Pin(5, Pin.OUT),rotation=2)
tft.init()
for second display
tft1 = gc9a01.GC9A01(spi,240,240,reset=Pin(9, Pin.OUT),cs=Pin(10, Pin.OUT),dc=Pin(46, Pin.OUT)backlight=Pin(5, Pin.OUT),rotation=2)
tft1.init()
after doing this process only second dispaly is turning on. Is there any method to use more than one display.

**Comment by russhughes** [comment]
I have run two displays using a Raspberry Pi Pico. I have not tried using an ESP32 but it should work. I'll look into it.
