### ISSUE TITLE
convert image to python module   

### ISSUE THREAD

**Issue by ALable** [russhughes/gc9a01_mpy#4]
**I want to realize the project about convert image to python module ,but when I  use the command  python ./imgtobitmap.py t1.png 3 >test.py**
an error message:  

> img = img.convert("P", palette=Image.ADAPTIVE, colors=2**bits)
>  Traceback (most recent call last):
> 
>   File "./imgtobitmap.py", line 101, in <module>
>     main()
>   File "./imgtobitmap.py", line 43, in main
>     ((palette[color*3] & 0xF8) << 8)
> IndexError: list index out of range

so I change the parameter (bits) to 2 . Luckily, it succeed ,but I execute the project code  a new error coming:

> Traceback (most recent call last):
>   File "<stdin>", line 60, in <module>
>   File "<stdin>", line 59, in main
> TypeError: can't convert str to int

Maybe the error  caused  by  the parameter(bits)

Here are my codes:
```
from machine import Pin, SPI
import gc9a01
import test


def main():
    '''
    Draw and move sprite
    '''
    spi = SPI(2, baudrate=60000000, sck=Pin(18), mosi=Pin(23))
    tft = gc9a01.GC9A01(
        spi,
        240,
        240,
        reset=Pin(26, Pin.OUT),
        cs=Pin(5, Pin.OUT),
        dc=Pin(27, Pin.OUT),
        backlight=Pin(2, Pin.OUT),
        rotation=0)

    # enable display and clear screen
    tft.init()
    tft.fill(gc9a01.BLACK)

  
    tft.bitmap(test,50,50)
main() 
```

Convert result  Test.py
```
HEIGHT = 64
WIDTH = 64
COLORS = 4
BITS = 8192
BPP = 2
PALETTE = [0x0000,0x4049,0x609b,0x4082]
```
![image](https://user-images.githubusercontent.com/105502871/185358320-469799b5-998d-480d-b543-89f98a0e0ca1.png)

**Comment by russhughes** [comment]
That should be fixed now.
