### ISSUE TITLE
issue with drawing lines : GC9A01.line(x0, y0, x1, y1, color)

### ISSUE THREAD

**Issue by kiridashi** [russhughes/gc9a01_mpy#5]
thank you very much for this great code and project,
which im trying to adapt to my pi pico with a round display (waveshare),
however, lately i ran in to some issues using the draw-line command.
i created a function for drawing lines as markers for a gauge:

```
#draw scala
def scala():
    r1=100
    r2=120
    for alpha in range (0,360,2):
        x1=int((r1*(math.cos((alpha-90)/180*math.pi))))
        y1=int((r1*(math.sin((alpha-90)/180*math.pi))))
        x1=x1+120
        y1=y1+120
        x2=int((r2*(math.cos((alpha-90)/180*math.pi))))
        y2=int((r2*(math.sin((alpha-90)/180*math.pi))))
        x2=x2+120
        y2=y2+120
        print ("alpha:",alpha,"x1:",x1,"y1:",y1,"x2:",x2,"y2:",y2)
        tft.line(x1,y1,x2,y2,0xFFFF)

scala()
```
but the area around 180 degree stays empty,
so i tried a single command:
`tft.line(120,220,120,240,0xFFFF)`
but had no result either ... is there maybe something wrong in the way i handle your routine ?

**Comment by russhughes** [comment]
The display coordinates should be between 0 and 239. Using 240 might be causing the whole line to be clipped.
